### ISSUE TITLE
Question regarding SRRF parameters w.r.t NanoJ-SRRF

### ISSUE THREAD

**Issue by WootaMelon** [HenriquesLab/NanoPyx#112]
Hello!

I just wanted to ask some questions regarding some parameters for SRRF that are currently not present in NanoPyx but are present in NanoJ-SRRF.

I noticed that the parameters "Axes in Ring" and "Max temporal analysis block size" found in NanoJ-SRRF are currently not present in NanoPyx's SRRF function. 

I wanted to kindly ask whether these parameters are currently being set automatically or are yet to be implemented.

Thank you for your help!

**Comment by inesmcunha** [comment]
Hello! 

Yes, those parameters are no longer used in the NanoPyx version. "Axes in Ring" now has a fixed value (the recommended to be used in all cases). "Max temporal analysis block size" is no longer a parameter because in NanoPyx you can manually change the block size (as a slider) for the temporal analysis (so there was no need for a maximum value as an extra parameter).

I hope this answered your question! SRRF in NanoPyx is completely ready to be used :)
Thanks and all the best!
Inês

**Comment by WootaMelon** [comment]
Hello Inês,

I really appreciate the quick and detailed reply, thanks!

I am currently using NanoJ in Java and got really excited when NanoPyx was released as Python is more flexible in terms of adaptation and support.

I understand that NanoPyx is still in development and wanted to say major kudos for the team’s dedication in developing NanoPyx. 

One more question, I also realized that the parameters I am using in NanoJ-SRRF's advanced options, “Gradient Smoothing” and “Gradient Weighting”, are missing from NanoPyx. can you please pinpoint me to the Java version of the code? I am trying to use these advanced option parameters in my analysis.

Thanks again!

**Comment by inesmcunha** [comment]
Hello,

Sorry for the late reply! Here you will find the java code for the NanoJ-SRRF: https://github.com/HenriquesLab/NanoJ-SRRF/blob/master/SRRF/src/nanoj/srrf/java/SRRF.java The parameters "doGradWeight" and "doGradSmooth" refer to the gradient weighting and gradient smoothing.

All the best,
Inês
